# -*- coding: utf-8 -*-
"""Cópia de CURRICULO_RAFAEL/ CSS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aDB9uI4HsduMLzMeXk6aUF2kSs4NougZ
"""

css


.left-aligned {
    float: left;
    margin-right: 20px; /* Adicionando um espaço entre a imagem e o texto */
    }
/* imagem */
.resized {
    margin: 50px;
    width: 150px; /* Definindo a largura da imagem */
    height: auto; /* A altura será ajustada automaticamente de acordo com a largura */
}

    .imagem-3x4 {
        width: 300px;
        height: 400px;
    }


.section-spacing {
            margin-bottom: 20px;
}

.name {
    color:#FFFFFF;
}

table
{
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
}

th,

td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

th {
            background-color: #f2f2f2;
        }

        tr:nth-child(even) {
            background-color: #f9f9f9;
        }

.linkedin-button {
            display: inline-block;
            padding: 10px 20px;
            background-color: #0077B5; /* Cor padrão do LinkedIn */
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
        }

        /* Estilo para quando o mouse passa por cima do botão */
        .linkedin-button:hover {
            background-color: #005e8e; /* Cor mais escura ao passar o mouse */
        }

.github-button {
            display: inline-block;
            padding: 10px 20px;
            background-color: #333;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
        }

.github-button:hover {
            background-color: #555;

    }
.email-button {
    display: inline-block;
    padding: 10px 20px;
    background-color: #0077B5; /* Cor padrão do LinkedIn */
    color: #fff;
    text-decoration: none;
    border-radius: 5px;
    }

/* Estilo para quando o mouse passa por cima do botão */
.email-button:hover {
    background-color: #005e8e; /* Cor mais escura ao passar o mouse */
    }

body {
    font-family: Arial, sans-serif;
    margin: 20px;
    padding: 10;
    background-color: #FFFFFF;
    }

header {
    text-align: center;
    padding: 20px 0;
    background-color: #333;
    color: #fff;
    font-family: "binnerD";
    }

section {
    max-width: 800px;
    margin: 20px auto;
    padding: 20px;
    background-color: #fff;
    border-radius: 8px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }


h1,

h2{
    font-family: 'Times New Roman', Times, serif;
    }

h3 {
    color: #333;
    }

ul {
    list-style-type: none;
    padding: 0;
    }

li {
    margin-bottom: 8px;
    }

    button{
    width: 200px;
    height: 100px;
}